[package]
name = "bike01"
version = "0.1.0"
authors = ["kazuha <mami.tomoe4@gmail.com>"]

[dependencies]
rocket = "*"
rocket_codegen = "*"
serde_derive = "*"
serde = "*"

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["tera_templates"]
